### ISSUE TITLE
Remove the CLI.zip from the SMP/E install

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-smpe-packaging#28] opened 2019-09-16 16:26 UTC
smpe-packaging build has smpe.sh script that points to a convenience build and also a CLI.  
This item is for the removal of the CLI from the smpe.sh script and it being delivered in the smpe distribution

**Comment by stevenhorsman** [comment] 2019-09-18 14:24
Duplicate of https://github.com/zowe/zowe-install-packaging/issues/680

**Closed by stevenhorsman** 2019-09-18 14:24 UTC
